/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vues;

import javax.swing.JFrame;

/**
 *
 * @author Hakim Mamar
 */
public class Gui extends javax.swing.JFrame {
    
    PanelChambre pCh;
    PanelClient pCl;
    PanelReservation pRes;
    int with = 700;
    int height = 500;

    /**
     * Creates new form Gui
     */
    public Gui() {
        initComponents();
        // creation panel pour les chambres
        pCh = new PanelChambre();
        pCh.setSize(with, height);
        // creation panel pour clients
        pCl = new PanelClient();
        pCl.setSize(with, height);
        // creation panel pour reservation
        pRes = new PanelReservation();  
        pRes.setSize(with, height);
        // ajouter les panels au panel principal
        PanelPrincipale.add(pCh);
        PanelPrincipale.add(pCl);
        PanelPrincipale.add(pRes);
        //affichage du panel reservation par defaut
        pCh.setVisible(false);
        pCl.setVisible(false);
        pRes.setVisible(true);
        
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setResizable(false);
        this.setSize(with, height);
        this.setLocationRelativeTo(null);
        this.setTitle(" Gestion de Reservation d'hotel");
        
        //charger la liste de chambre au demarrage
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipale = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mCl = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        mCh = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        miAffichageChambre = new javax.swing.JMenuItem();
        mRes = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout PanelPrincipaleLayout = new javax.swing.GroupLayout(PanelPrincipale);
        PanelPrincipale.setLayout(PanelPrincipaleLayout);
        PanelPrincipaleLayout.setHorizontalGroup(
            PanelPrincipaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 605, Short.MAX_VALUE)
        );
        PanelPrincipaleLayout.setVerticalGroup(
            PanelPrincipaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 432, Short.MAX_VALUE)
        );

        getContentPane().add(PanelPrincipale, java.awt.BorderLayout.CENTER);

        mCl.setText("Client");

        jMenuItem1.setText("Ajouter un client");
        mCl.add(jMenuItem1);

        jMenuItem2.setText("Afficher liste Clients");
        mCl.add(jMenuItem2);

        jMenuBar1.add(mCl);

        mCh.setText("Chambre");

        jMenuItem3.setText("Ajouter nouvelle chambre");
        mCh.add(jMenuItem3);

        miAffichageChambre.setText("Afficher liste de chambres");
        miAffichageChambre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAffichageChambreActionPerformed(evt);
            }
        });
        mCh.add(miAffichageChambre);

        jMenuBar1.add(mCh);

        mRes.setText("Reservation");

        jMenuItem5.setText("Ajouter reservation");
        mRes.add(jMenuItem5);

        jMenuItem6.setText("Afficher liste reservation");
        mRes.add(jMenuItem6);

        jMenuBar1.add(mRes);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miAffichageChambreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAffichageChambreActionPerformed
        // TODO add your handling code here:
        pCh.setVisible(true);
        pCl.setVisible(false);
        pRes.setVisible(false);        
        
        
       
       
        
    }//GEN-LAST:event_miAffichageChambreActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPrincipale;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenu mCh;
    private javax.swing.JMenu mCl;
    private javax.swing.JMenu mRes;
    private javax.swing.JMenuItem miAffichageChambre;
    // End of variables declaration//GEN-END:variables
}
