/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vues;

import javax.swing.JFrame;

/**
 *
 * @author Hakim Mamar
 */
public class Gui extends javax.swing.JFrame {
    
    PanelChambre pCh;
    PanelClient pCl;
    PanelReservation pRes;
    int with = 700;
    int height = 500;

    /**
     * Creates new form Gui
     */
    public Gui() {
        initComponents();
        // creation panel pour les chambres
        pCh = new PanelChambre();
        pCh.setSize(with, height);
        // creation panel pour clients
        pCl = new PanelClient();
        pCl.setSize(with, height);
        // creation panel pour reservation
        pRes = new PanelReservation();  
        pRes.setSize(with, height);
        // ajouter les panels au panel principal
        PanelPrincipale.add(pCh);
        PanelPrincipale.add(pCl);
        PanelPrincipale.add(pRes);
        //affichage du panel reservation par defaut
        pCh.setVisible(false);
        pCl.setVisible(false);
        pRes.setVisible(true);
        
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setResizable(false);
        this.setSize(with, height);
        this.setLocationRelativeTo(null);
        this.setTitle(" Gestion de Reservation d'hotel");
        
        //charger la liste de chambre au demarrage
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipale = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mCl = new javax.swing.JMenu();
        miAjouterClient = new javax.swing.JMenuItem();
        miAfficherClient = new javax.swing.JMenuItem();
        mCh = new javax.swing.JMenu();
        miAjouterChambre = new javax.swing.JMenuItem();
        miAffichageChambre = new javax.swing.JMenuItem();
        mRes = new javax.swing.JMenu();
        miAjouterReservation = new javax.swing.JMenuItem();
        miAfficherReservation = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout PanelPrincipaleLayout = new javax.swing.GroupLayout(PanelPrincipale);
        PanelPrincipale.setLayout(PanelPrincipaleLayout);
        PanelPrincipaleLayout.setHorizontalGroup(
            PanelPrincipaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 605, Short.MAX_VALUE)
        );
        PanelPrincipaleLayout.setVerticalGroup(
            PanelPrincipaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 432, Short.MAX_VALUE)
        );

        getContentPane().add(PanelPrincipale, java.awt.BorderLayout.CENTER);

        mCl.setText("Client");

        miAjouterClient.setText("Ajouter un client");
        miAjouterClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAjouterClientActionPerformed(evt);
            }
        });
        mCl.add(miAjouterClient);

        miAfficherClient.setText("Afficher liste Clients");
        miAfficherClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAfficherClientActionPerformed(evt);
            }
        });
        mCl.add(miAfficherClient);

        jMenuBar1.add(mCl);

        mCh.setText("Chambre");

        miAjouterChambre.setText("Ajouter nouvelle chambre");
        miAjouterChambre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAjouterChambreActionPerformed(evt);
            }
        });
        mCh.add(miAjouterChambre);

        miAffichageChambre.setText("Afficher liste de chambres");
        miAffichageChambre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAffichageChambreActionPerformed(evt);
            }
        });
        mCh.add(miAffichageChambre);

        jMenuBar1.add(mCh);

        mRes.setText("Reservation");

        miAjouterReservation.setText("Ajouter reservation");
        miAjouterReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAjouterReservationActionPerformed(evt);
            }
        });
        mRes.add(miAjouterReservation);

        miAfficherReservation.setText("Afficher liste reservation");
        miAfficherReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAfficherReservationActionPerformed(evt);
            }
        });
        mRes.add(miAfficherReservation);

        jMenuBar1.add(mRes);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miAffichageChambreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAffichageChambreActionPerformed
        // TODO add your handling code here:
        pCh.setVisible(true);
        pCl.setVisible(false);
        pRes.setVisible(false);    
        
    }//GEN-LAST:event_miAffichageChambreActionPerformed

    private void miAjouterClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAjouterClientActionPerformed
        // TODO add your handling code here:
        pCh.setVisible(false);
        pCl.setVisible(true);
        pRes.setVisible(false);
    }//GEN-LAST:event_miAjouterClientActionPerformed

    private void miAfficherClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAfficherClientActionPerformed
        // TODO add your handling code here:
        pCh.setVisible(false);
        pCl.setVisible(true);
        pRes.setVisible(false);
        
    }//GEN-LAST:event_miAfficherClientActionPerformed

    private void miAjouterChambreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAjouterChambreActionPerformed
        // TODO add your handling code here:
        pCh.setVisible(true);
        pCl.setVisible(false);
        pRes.setVisible(false);
    }//GEN-LAST:event_miAjouterChambreActionPerformed

    private void miAjouterReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAjouterReservationActionPerformed
        // TODO add your handling code here:
        pCh.setVisible(false);
        pCl.setVisible(false);
        pRes.setVisible(true);
    }//GEN-LAST:event_miAjouterReservationActionPerformed

    private void miAfficherReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAfficherReservationActionPerformed
        // TODO add your handling code here:
        pCh.setVisible(false);
        pCl.setVisible(false);
        pRes.setVisible(true);
    }//GEN-LAST:event_miAfficherReservationActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPrincipale;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mCh;
    private javax.swing.JMenu mCl;
    private javax.swing.JMenu mRes;
    private javax.swing.JMenuItem miAffichageChambre;
    private javax.swing.JMenuItem miAfficherClient;
    private javax.swing.JMenuItem miAfficherReservation;
    private javax.swing.JMenuItem miAjouterChambre;
    private javax.swing.JMenuItem miAjouterClient;
    private javax.swing.JMenuItem miAjouterReservation;
    // End of variables declaration//GEN-END:variables
}
