/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vues;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import modele.Chambre;
import modele.ListeChambres;
import persistance.ManipulationFichiers;

/**
 *
 * @author Hakim Mamar
 */
public class PanelChambre extends javax.swing.JPanel {
    
    ListeChambres listeChambre;

    /**
     * Creates new form PanelChambre
     */
    public PanelChambre() {
        initComponents();
        
        listeChambre = new ListeChambres();
        ManipulationFichiers.lireFichierChambre(listeChambre);
       
    }

    public JTable getTabChambre() {
        return tabChambre;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupBtCh = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        tNo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        rbSimple = new javax.swing.JRadioButton();
        rbDouble = new javax.swing.JRadioButton();
        rbSuite = new javax.swing.JRadioButton();
        rbJunior = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabChambre = new javax.swing.JTable();
        btAffichage = new javax.swing.JButton();
        btAjouter = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setText("Numero");

        jLabel2.setText("Prix");

        groupBtCh.add(rbSimple);
        rbSimple.setText("Chambre Simple");

        groupBtCh.add(rbDouble);
        rbDouble.setText("Chambre double");

        groupBtCh.add(rbSuite);
        rbSuite.setText("Suite");
        rbSuite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSuiteActionPerformed(evt);
            }
        });

        groupBtCh.add(rbJunior);
        rbJunior.setText("Suite Junior");

        tabChambre.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero", "Type", "Prix", "Disponible"
            }
        ));
        jScrollPane1.setViewportView(tabChambre);

        btAffichage.setText("Afficher la liste de chambre");
        btAffichage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAffichageActionPerformed(evt);
            }
        });

        btAjouter.setText("Ajouter la Chambre");
        btAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAjouterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tNo)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(rbJunior, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rbSimple, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rbDouble, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                .addComponent(rbSuite, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(btAjouter)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btAffichage)
                        .addGap(108, 108, 108))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addComponent(rbSimple)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbSuite)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbDouble)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbJunior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btAjouter))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btAffichage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(198, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rbSuiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSuiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbSuiteActionPerformed

    private void btAffichageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAffichageActionPerformed
        // TODO add your handling code here:
        
         
        
        Object row[] = new Object[4];
        DefaultTableModel dataModel = (DefaultTableModel) tabChambre.getModel();
       // jTable1.setModel(dataModel);
        for (Chambre ch : listeChambre) {

            row[0] = ch.getNumero();
            row[1] = ch;
            row[2] = ch.getPrix();
            if(ch.isDisponible()){
               row[3] =  "oui";
            }else{
                 row[3] = "non";
            }
                
           
            dataModel.addRow(row);

        }
    }//GEN-LAST:event_btAffichageActionPerformed

    private void btAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAjouterActionPerformed
        // TODO add your handling code here:
        //rbSimple.get
        
        if(rbDouble.isSelected()){
            System.out.println("Chambre double");
        }
    }//GEN-LAST:event_btAjouterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAffichage;
    private javax.swing.JButton btAjouter;
    private javax.swing.ButtonGroup groupBtCh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton rbDouble;
    private javax.swing.JRadioButton rbJunior;
    private javax.swing.JRadioButton rbSimple;
    private javax.swing.JRadioButton rbSuite;
    private javax.swing.JTextField tNo;
    private javax.swing.JTable tabChambre;
    // End of variables declaration//GEN-END:variables
}
